# Generated by Django 4.2.6 on 2024-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(max_length=50)),
                ('movement_type', models.CharField(max_length=50)),
                ('muscle_group', models.CharField(max_length=50)),
                ('major_muscle', models.CharField(max_length=50)),
                ('minor_muscle', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('modifications', models.TextField()),
                ('beginner', models.BooleanField()),
                ('intermediate', models.BooleanField()),
                ('advanced', models.BooleanField()),
                ('warmup', models.BooleanField()),
            ],
        ),
    ]
