# Generated by Django 4.2.6 on 2024-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('activity_level', models.CharField(max_length=10)),
                ('calorie_goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
    ]
