# Generated by Django 4.2.6 on 2024-04-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_dailycalorierequirement_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(),
        ),
    ]
