# Generated by Django 4.2.6 on 2024-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_recipe_calories_alter_recipe_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_low', models.IntegerField()),
                ('age_high', models.IntegerField()),
                ('male_low_activity', models.IntegerField()),
                ('male_moderate_activity', models.IntegerField()),
                ('male_high_activity', models.IntegerField()),
                ('female_low_activity', models.IntegerField()),
                ('female_moderate_activity', models.IntegerField()),
                ('female_high_activity', models.IntegerField()),
            ],
        ),
    ]
