# Generated by Django 4.2.6 on 2024-04-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_calorierequirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCalorieRequirement',
        ),
    ]
