# Generated by Django 4.2.6 on 2024-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_weightentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.CharField(choices=[('light', 'Light activity - Once a week'), ('moderate', 'Moderate activity - 2/3 times a week'), ('intense', 'Intense activity - 4/5 days a week'), ('top_athlete', 'Top athlete - Every day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal_activity_level',
            field=models.CharField(choices=[('moderate', 'Moderate activity - 2/3 times a week'), ('intense', 'Intense activity - 4/5 days a week'), ('top_athlete', 'Top athlete - Every day')], max_length=20),
        ),
    ]
